# Data Science Numpy & CSV's

## Tasks Today:

1) <b>Numpy</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Python List Comparison <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) In-Class Exercise #1 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Importing <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Creating an NDArray <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.array() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.zeros() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.ones() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.arange() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Making Lists into NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; e) Performing Calculations on NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Summation <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Difference <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Multiplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Division <br>
 &nbsp;&nbsp;&nbsp;&nbsp; f) Numpy Subsetting <br>
 &nbsp;&nbsp;&nbsp;&nbsp; g) Multi-dimensional Arrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; h) Indexing NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; i) Checking NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; j) Altering NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; k) Checking the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; l) Altering the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; m) In-Class Exercise #2 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; n) Complex Indexing & Assigning <br>
 &nbsp;&nbsp;&nbsp;&nbsp; o) Elementwise Multplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp; p) np.where() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; q) Random Sampling <br>

2) <b>Working With CSV's</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Imports <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) Reading a CSV <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Loading a CSV's Data <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Checking Number of Records <br>
 
3) <b>Exercises</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) #1 - Calculate BMI with NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) #2 - Find the Average Sum of Marathon Runners <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) #3 - Random Matrix Function <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) #4 - Comparing Boston Red Sox Hitting Numbers <br>

## Numpy <br>

<p>NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.</p>
<ul>
    <li>Shape = Rows & Columns</li>
    <li>Matrix = Entire Array</li>
    <li>Vector = Variables to be applied (same vector as the one used in physics)</li>
    <li>Array = Similar to lists</li>
</ul>

#### Python List Comparison

<p>Lists are flexible, dynamic python objects that do their job quite well. But they do not support some mathematical operations in an intuitive way. Consider the summation of two lists, $l_1$ and $l_2$</p>

In [1]:
# Pandas build on top of numpy



In [6]:
# create two lists and sum both of them together (results may not be what you expect)

l_1 = [1,2,3]
l_2 = [4,5,6]

print(f"Summation of a regular python list: {l_1 + l_2}")
print(f"Finding the difference of a regular python list: {l_1 - l_2}")

Summation of a regular python list: [1, 2, 3, 4, 5, 6]


TypeError: unsupported operand type(s) for -: 'list' and 'list'

<p>If we wanted to sum lists elementwise, we could write our own function that does the job entirely within the framework of python</p>

#### In-Class Exercise #1 - Write a function that sums the indexes of two lists <br>
<p>Ex: [2, 3, 4] + [1, 5, 2] = [3, 8, 6]</p>

In [7]:
l_1 = [2,3,4]
l_2 = [1,5,2]
l_3 = []

for i in range(len(l_1)):
    l_3.append(l_1[i] + l_2[i])
print(l_3)

[3, 8, 6]


#### Importing

In [8]:
# always import as np, standard across all of data science
# !pip install numpy
import numpy as np

#### Creating an NDArray <br>
<p>NumPy is based around a class called the $\textit{NDArray}$, which is a flexible vector / matrix class that implements the intuitive matrix and vector arithmatic lacking in basic Python. Let's start by creating some NDArrays:</p>

###### - np.array()

In [9]:
arr1 = np.array([1,2,3])
arr1
# print(type(arr1))

array([1, 2, 3])

###### - np.zeros()

In [10]:
# Shape -- np.zeros() has a parameter of "shape" that must be given
arr_zeros = np.zeros((3,3))
arr_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

###### - np.ones()

In [11]:
arr_ones = np.ones((3,3))
arr_ones = np.ones((3,3), int)
arr_ones

# notice no dots after the numbers, because we specified the datatype to be integer

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

###### - np.arange()

In [12]:
arr_range = np.arange(1,12)
arr_range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

###### - Making Lists into NDArrays

In [13]:
list_1 = [5,6,7]

arr_list = np.array(list_1)
arr_list

array([5, 6, 7])

#### Performing Calculations on NDArrays

###### - Summation

In [14]:
arr_list1 = np.array([5,10,15,20,25])
arr_list2 = np.array([10,20,30,40,50])

result_sum = arr_list1 + arr_list2
result_sum



array([15, 30, 45, 60, 75])

###### - Difference

In [15]:
result_diff = arr_list2 - arr_list1
result_diff

array([ 5, 10, 15, 20, 25])

###### - Multiplication

In [16]:
result_mul = arr_list2 * arr_list1
result_mul

array([  50,  200,  450,  800, 1250])

###### - Division

In [17]:
result_div = arr_list2 / arr_list1
result_div

array([2., 2., 2., 2., 2.])

#### Modulo

In [18]:
result_mod = arr_list2 % arr_list1
result_mod

array([0, 0, 0, 0, 0])

#### Floor Division

In [19]:
result_floor = arr_list2 // arr_list1
result_floor

array([2, 2, 2, 2, 2])

#### Numpy Subsetting

In [20]:
# result3 <= 800
print(result_mul <= 800)
print(result_mul[result_mul <= 800])

# test_ndStrings = np.array(['Bob','Mark','Angelica','Barb'])
# print(test_ndStrings[test_ndStrings[0] == 'B'])

# conditioal check, returns true or false
# print(arr1 < 2)
# print(arr2 >= 2)

# conditional check, that returns the elements that meet the given condition


[ True  True  True  True False]
[ 50 200 450 800]


#### Multi-dimensional Arrays <br>
<p>NumPy seamlessly supports multidimensional arrays and matrices of arbitrary dimension without nesting NDArrays. NDArrays themselves are flexible and extensible and may be defined with such dimensions, with a rich API of common functions to facilitate their use. Let's start by building a two dimensional 3x3 matrix by conversion from a nested group of core python lists $M = [l_0, l_1, l_2]$:</p>

In [21]:
aList = [0,1,2]
bList = [3,4,5]
cList = [6,7,8]

# first step: convert lists into a Matrix
M = [aList, bList, cList]
M

# second step: place Matrix inside NDArray
ND_M = np.array(M)
print(f"NDArray Structure {ND_M}")
ND_M


NDArray Structure [[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Indexing NDArrays <br>
<p> Similar to lists within lists; however, the syntax looks more like C programming language.... It is [1, 2] to access the second row, third element.</p>

In [22]:
print(f"Getting the Middle Element within the matrix: {ND_M[1,1]}")

Getting the Middle Element within the matrix: 4


#### Assigning Values in NDArrays

In [23]:
ND_M[1,1] = 9

ND_M

array([[0, 1, 2],
       [3, 9, 5],
       [6, 7, 8]])

<p>Notice above how we ended up with a 1 in the target element's place. This is a data type issue. The .dtype() method is supported by all NDArrays, as well as the .astype() method for casting between data types:</p>

#### Checking NDArray Type

In [24]:
# usind the .dtype() method
nd_type = ND_M.dtype

nd_type

dtype('int64')

#### Altering NDArray Type

In [25]:
result_t = nd_type
print(f"Type before change: {result_t}")

changed = ND_M.astype(np.float32)
changed = ND_M.astype(np.int32)
changed = ND_M.astype(np.float64)

result_changed = changed

print(f"Type after change: {result_changed.dtype}")

Type before change: int64
Type after change: float64


In [26]:
# Checking the Shape of the ND_M Numpy Array
# Using the method .shape


#### Checking the Shape <br>
<p>The behavior and properties of an NDArray are often sensitively dependent on the $\textit{shape}$ of the NDArray itself. The shape of an array can be found by calling the .shape method, which will return a tuple containing the array's dimensions:</p>

In [75]:
 # shape is always rows x columns
# Checking the Shape of the ND_M Numpy Array
# Using the method .shape
result_changed.shape
print(result_changed.shape)

result_3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
result_3.shape

a = np.float64
result_3 = result_3.astype(a)
print(result_3)


(3, 3)
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]


#### Altering the Shape <br>
<p>As long as the number of elements remains fixed, we can reshape NDArrays at will:</p>

In [28]:
# Change the shape of the numpy array
# Using the method .reshape()

# The reshape should be a multiple of the original shape
# Meaning we can have a shape of (1,9) or (9,1) or (3,3)

# (9,1) == 9 rows , 1 column

print(result_changed.reshape((9,1)))
print(result_3.reshape(1,2,4))
print(result_3.reshape(2,4))
print(result_3.reshape(2,2,2))

result_3.reshape(2,2,2)



[[0.]
 [1.]
 [2.]
 [3.]
 [9.]
 [5.]
 [6.]
 [7.]
 [8.]]
[[[1 2 3 4]
  [5 6 7 8]]]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
# keep in mind that the shape numbers do matter, (9, 1) is different than (1, 9)


#### In-Class Exercise #2 - Create a matrix of range 0 up to 16 and reshape it into a 4x4 matrice

In [29]:
matrix_16 = np.arange(0,16).reshape(4,4)
print(matrix_16 )

matrix_9_3 = np.arange(1,65).reshape(2,4,8)
print(matrix_9_3)

print(matrix_9_3.shape)

print(matrix_9_3[1,2,3])

print(matrix_9_3 > 20)

print(matrix_9_3[matrix_9_3 > 20])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[[ 1  2  3  4  5  6  7  8]
  [ 9 10 11 12 13 14 15 16]
  [17 18 19 20 21 22 23 24]
  [25 26 27 28 29 30 31 32]]

 [[33 34 35 36 37 38 39 40]
  [41 42 43 44 45 46 47 48]
  [49 50 51 52 53 54 55 56]
  [57 58 59 60 61 62 63 64]]]
(2, 4, 8)
52
[[[False False False False False False False False]
  [False False False False False False False False]
  [False False False False  True  True  True  True]
  [ True  True  True  True  True  True  True  True]]

 [[ True  True  True  True  True  True  True  True]
  [ True  True  True  True  True  True  True  True]
  [ True  True  True  True  True  True  True  True]
  [ True  True  True  True  True  True  True  True]]]
[21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44
 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]


#### Complex Indexing & Assinging

In [30]:
M = np.zeros((5,6))
print("resetting matrix")
print("before assignment")
print(M)

# set every first element in each row to 1
M[:,0] = 1
print('\n after assigning 1 to first column:')
print(M)

#set all eleemnts in axis 3 to 5 (excluding 5) = 5
M[2:5, :] = 5
print('\n after assigning 5 to rows 3-5')
print(M)

# reset the matrix back to 0
print('\n reset to zero')
M = M * 0
print(M)

#set the second and third columns to a number == 2
M[:,1:3] = 2
print('\n assigning 2 to 2nd and 3rd rows')
print(M)


M3 = np.zeros((3,3,3))
print('\n', M3)

M3 *= 0
M3[:,1,1] = 1
print('\n', M3)

M3 *= 0
for i in range(len(M3)):
    M3[i,i,i] = 1
print('\n', M3)

# creating a vector in numpy
x = np.arange(6)

# reset matrix to 0
M *= 0

#set the first row to that range of vector numbers we just created 
M[0, :] = x
print('\n assigning vector array x to the first axis in the matrix')
print(M)


resetting matrix
before assignment
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

 after assigning 1 to first column:
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]

 after assigning 5 to rows 3-5
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]]

 reset to zero
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

 assigning 2 to 2nd and 3rd rows
[[0. 2. 2. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0.]]

 [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]

 [[[0. 0. 0.]
  [0. 1. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 1. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 1. 0.]
  [0. 0. 0.]]]

 [[[1. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 1. 0

#### Elementwise Multiplication

<p>As long as the shapes of NDArrays are 'compatible', they can be multiplied elementwise, broadcasted, used in inner products, and much much more. 'Compatible' in this context can mean compatible in the linear algebraic sense, i.e. for inner products and other matrix multiplication, or simply sharing a dimension in such a manner that broadcasting 'makes sense'. Here are some examples of this:</p>

In [31]:
from numpy import dot

# initialize a vecotr of range 6, then reset matrix to zero and run vector multiplication on the matrix
v = M[:, :] = 0
print(v)

# reset the matrix to 0
M = M * v
print(M)

A = np.arange(1,10).reshape((3,3))
B = np.arange(10,19).reshape((3,3))
C = np.arange(5,14).reshape((3,3))
print(A)
print(B)
print(C)

print(dot(A,B))
print(dot(B,A))
print(dot(dot(A,B),C))
print(dot(A,dot(B,C)))
print(dot(A + B, C))
print(dot(A,C) + dot(B,C))

0
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
[[138 171 204]
 [174 216 258]
 [210 261 312]]
[[ 2196  2466  2736]
 [ 5274  5922  6570]
 [ 8352  9378 10404]]
[[ 2196  2466  2736]
 [ 5274  5922  6570]
 [ 8352  9378 10404]]
[[324 363 402]
 [468 525 582]
 [612 687 762]]
[[324 363 402]
 [468 525 582]
 [612 687 762]]


#### np.where() <br>
<p>If statement within NDArrays that allows you to run conditionals on the entire array</p>

In [48]:
print(result_mul)
print('\n', np.where(result_mul < 800))

print(result_mul[np.where(result_mul < 800)])
result_mul[[0,1,2]]

#transform data based on boolean mask == True
result_mul[np.where(result_mul < 800)] = 300
print('\n', result_mul)


[ 300  300  300  800 1250]

 (array([0, 1, 2]),)
[300 300 300]

 [ 300  300  300  800 1250]
[2 3 4]


#### Random Sampling <br>
<p>NumPy provides machinery to work with random numbers - something often needed in a broad spectrum of data science applications.</p>

In [49]:
# np.random.uniform()

# A single call generates a single random number between 0 and 1

print('Here is a random number: %s' % np.random.uniform())

# You can also pass some parameters or bounds

print('Here is a random number between 0 and 1 Million: %s' % np.random.uniform(0, 1e6))

# You can also generate a bunch of random numbers all at once

print('Here are 5 random numbers between 0 and 10: %s' % np.random.uniform(0, 10, 5))

# Even matrices with shapes as a parameter

print('Here is a 3x3 matrix with numbers between 0 and 10: \n %s' % np.random.uniform(0, 10, (3, 3)))

Here is a random number: 0.9537200921174694
Here is a random number between 0 and 1 Million: 48839.06598371002
Here are 5 random numbers between 0 and 10: [2.35076891 2.6188707  1.7027307  2.39171009 3.49569143]
Here is a 3x3 matrix with numbers between 0 and 10: 
 [[7.23806664 4.0342979  1.02172336]
 [5.17461822 4.80507549 0.23434554]
 [8.71435831 0.10805505 6.66960944]]


## Working With CSV's

#### Imports

In [52]:
import csv
import numpy as np
from datetime import datetime

#### Reading a CSV

In [54]:
# Creating Function to open and read CSV data
def open_csv(filename, d = ','):
    # define an empty list to store data
    data = []
    
    with open(filename, encoding = 'utf-8') as mData:
        # use the csv reader method to create a python list
        info = csv.reader(mData, delimiter = d)
        
        # loop over info and append to data list
        for row in info:
            data.append(row)
    return data

csv_data = open_csv('../files/boston_marathon2017_edited.csv')

print(csv_data[1:5])

[['12/30/1899 12:30:28 AM', '12/30/1899 12:45:44 AM', '12/30/1899 1:01:15 AM', '12/30/1899 1:16:59 AM', '12/30/1899 1:33:01 AM', '12/30/1899 1:48:19 AM', '12/30/1899 2:02:53 AM', '12/30/1899 12:15:25 AM', '24', '11', '7777', 'KEN', '7777', '', 'Keringet', 'KEN', '1', '1', '12/30/1899 1:04:35 AM', 'M', 'Kirui, Geoffrey', '1', '12/30/1899 2:09:37 AM', '1', '12/30/1899 12:04:57 AM', ''], ['12/30/1899 12:30:27 AM', '12/30/1899 12:45:44 AM', '12/30/1899 1:01:15 AM', '12/30/1899 1:16:59 AM', '12/30/1899 1:33:01 AM', '12/30/1899 1:48:19 AM', '12/30/1899 2:03:14 AM', '12/30/1899 12:15:24 AM', '30', '17', '7798', 'USA', '7798', '', 'Portland', 'USA', '2', '2', '12/30/1899 1:04:35 AM', 'M', 'Rupp, Galen', '1', '12/30/1899 2:09:58 AM', '2', '12/30/1899 12:04:58 AM', 'OR'], ['12/30/1899 12:30:29 AM', '12/30/1899 12:45:44 AM', '12/30/1899 1:01:16 AM', '12/30/1899 1:17:00 AM', '12/30/1899 1:33:01 AM', '12/30/1899 1:48:31 AM', '12/30/1899 2:03:38 AM', '12/30/1899 12:15:25 AM', '25', '23', '7828', 'JP

#### Loading a CSV's Data 

In [62]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

# instead of loading csv normally, let's load it into a numpy array to calculate results on
def load_data(filename, d = ','):
    data = np.genfromtxt(filename, delimiter = d, skip_header = 1,
                        usecols = np.arange(0,24), invalid_raise = False,
                        names = FIELDS, dtype = DATATYPES)
    return data

bs2017 = load_data('../files/redsox_2017_hitting.txt')

print(bs2017)

names = bs2017['Name']
print(names)

#find total hits
total_hits = sum(bs2017['H'])
print(f'\n Total Hits 2017: {total_hits}')

# total home runs for the red sox 2017 team
total_HR = sum(bs2017['HR'])
print(f'\n Total Home Runs 2017: {total_HR}')



[( 1, b'C', b'Christian Vazquez', 26,  99, 345, 324,  43,  94, 18, 2,  5,  32,  7, 2, 17,  64, 0.29 , 0.33 , 0.404, 0.735,  91, 131, 14)
 ( 2, b'1B', b'Mitch Moreland', 31, 149, 576, 508,  73, 125, 34, 0, 22,  79,  0, 1, 57, 120, 0.246, 0.326, 0.443, 0.769,  99, 225, 14)
 ( 3, b'2B', b'Dustin Pedroia', 33, 105, 463, 406,  46, 119, 19, 0,  7,  62,  4, 3, 49,  48, 0.293, 0.369, 0.392, 0.76 , 100, 159, 11)
 ( 4, b'SS', b'Xander Bogaerts', 24, 148, 635, 571,  94, 156, 32, 6, 10,  62, 15, 1, 56, 116, 0.273, 0.343, 0.403, 0.746,  95, 230, 17)
 ( 5, b'3B', b'Rafael Devers', 20,  58, 240, 222,  34,  63, 14, 0, 10,  30,  3, 1, 18,  57, 0.284, 0.338, 0.482, 0.819, 111, 107,  5)
 ( 6, b'LF', b'Andrew Benintendi', 22, 151, 658, 573,  84, 155, 26, 1, 20,  90, 20, 5, 70, 112, 0.271, 0.352, 0.424, 0.776, 102, 243, 16)
 ( 7, b'CF', b'Jackie Bradley Jr.', 27, 133, 541, 482,  58, 118, 19, 3, 17,  63,  8, 3, 48, 124, 0.245, 0.323, 0.402, 0.726,  89, 194,  8)
 ( 8, b'RF', b'Mookie Betts', 24, 153, 712, 62

#### Summing the top 5 hitters for HR's

In [69]:
# find the top 5 hr hitters

# Step 1: Get all HR data into a variable
# Step 2: Get all Player Names
# Step 3: Create new list for new_names (empty to start)
# Step 4: Decode the player names into regular strings
# Step 5: Grab all data and place inside of a zipped list
# Step 6: Sort values based on HR data

# Step 1: 
all_hr = bs2017['HR']

# Step 2: 
all_names = bs2017['Name']

# Step 3:
new_names = []

# Step 4:
for name in range(len(all_names)):
    new_names.append(all_names[name].decode('utf-8'))
print(new_names)

# Step 5
zipped_values = list(zip(new_names,all_hr))
print(zipped_values)

# Step 6
sorted_hr = sorted(zipped_values, key = lambda x: x[1], reverse = True)
print(sorted_hr[0:6])

['Christian Vazquez', 'Mitch Moreland', 'Dustin Pedroia', 'Xander Bogaerts', 'Rafael Devers', 'Andrew Benintendi', 'Jackie Bradley Jr.', 'Mookie Betts', 'Hanley Ramirez', 'Sandy Leon', 'Chris Young', 'Deven Marrero', 'Eduardo Nunez', 'Brock Holt', 'Josh Rutledge', 'Pablo Sandoval', 'Sam Travis', 'Tzu-Wei Lin', 'Marco Hernandez', 'Rajai Davis', 'Steve Selsky', 'Blake Swihart', "Chase d'Arnaud"]
[('Christian Vazquez', 5), ('Mitch Moreland', 22), ('Dustin Pedroia', 7), ('Xander Bogaerts', 10), ('Rafael Devers', 10), ('Andrew Benintendi', 20), ('Jackie Bradley Jr.', 17), ('Mookie Betts', 24), ('Hanley Ramirez', 23), ('Sandy Leon', 7), ('Chris Young', 7), ('Deven Marrero', 4), ('Eduardo Nunez', 8), ('Brock Holt', 0), ('Josh Rutledge', 0), ('Pablo Sandoval', 4), ('Sam Travis', 0), ('Tzu-Wei Lin', 0), ('Marco Hernandez', 0), ('Rajai Davis', 0), ('Steve Selsky', 0), ('Blake Swihart', 0), ("Chase d'Arnaud", 0)]
[('Mookie Betts', 24), ('Hanley Ramirez', 23), ('Mitch Moreland', 22), ('Andrew Beni

# Exercises To Complete.... <br>
<p>Given in separate file after completion of this file</p>